version: '3.4'

services:
  authproject.api:
    image: ${DOCKER_REGISTRY-}authprojectapi
    build:
      context: .
      dockerfile: AuthProject.API/Dockerfile
    ports:
     - "8080:8080"
     - "8081:8081"
    depends_on:
      - authproject.database
  
  authproject.database:
   image: postgres:latest
   container_name: authproject.database
   environment:
    - POSTGRES_DB=postgres_db
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
   volumes:
    - ./.containers/postgres-db:/var/lib/postgresql/data
   ports:
    - 5432:5432 
  
